### ISSUE TITLE
Realizar o retorno de todas instituições e profissionais de saúde de um estado

### ISSUE THREAD

**Issue by victorMagalhaesPacheco** [kyriosdata/rnds#14]
Olá, estou em um processo de trabalho, no qual é necessário ter acesso a todas instituições e todos os profissionais de um determinado estado.

Realizei a integração através do webservice do CNES https://servicoshm.saude.gov.br/cnes/EstabelecimentoSaudeService/v1r0, mas o mesmo é extremamente limitado, principalmente pelo fato em que o mesmo limita as requisições, então se você fizer mais que 10 mil requisições em um curso período de tempo, o serviço bloqueia. Preciso realizar o a quantidade de requisições maior que isso, pois a quantidade de profissionais passam de 100 mil.

Tentei também através do CSV gerado no site do CNES, entretanto o mesmo vem mal formatado e o que complica pra automatizar a busca.

Você conhece alguma ferramenta que possamos através de uma requisição HTTP trazer todos os estados e profissionais de um estado ou cidade? Os dados principais são, estabelecimentos, profissionais e vinculos.

Obrigado.

**Comment by kyriosdata** [comment]
Olá Victor,

pelo volume eu descartaria o acesso via HTTP (apenas uma opinião). O que eu faria:

- obter a base de dados do CNES (ftp://ftp.datasus.gov.br/cnes/BASE_DE_DADOS_CNES_202106.ZIP). 
- preparar base intermediária, adequada para as minhas consultas, a partir daquela obtida acima.
- só então realizaria as consultas.

**Comment by victorMagalhaesPacheco** [comment]
> Olá Victor,
> 
> pelo volume eu descartaria o acesso via HTTP (apenas uma opinião). O que eu faria:
> 
> * obter a base de dados do CNES (ftp://ftp.datasus.gov.br/cnes/BASE_DE_DADOS_CNES_202106.ZIP).
> * preparar base intermediária, adequada para as minhas consultas, a partir daquela obtida acima.
> * só então realizaria as consultas.

Obrigado pelas informações.
Você conhece algum tutorial que possa restaurar todos aqueles csv em algum banco?

Obrigado.

**Comment by kyriosdata** [comment]
Não exatamente um tutorial, mas a documentação completa está em 
http://cnes.datasus.gov.br/pages/downloads/documentacao.jsp
