### ISSUE TITLE
EHR-ERR884: Os dados de autenticação informados são inválidos

### ISSUE THREAD

**Issue by gustavorps** [kyriosdata/rnds#15]
Obtive o `access_token` no endpoint [`https://ehr-auth-hmg.saude.gov.br/api/token`](https://ehr-auth-hmg.saude.gov.br/api/token) mas ao tentar utilizar obtenho o seguinte retorno:

```
curl --location -g --request GET 'https://ehr-services.hmg.saude.gov.br/api/fhir/r4/Organization/2486024' --header 'X-Authorization-Server: Bearer ACCESS_TOKEN --header 'Authorization;'

{"resourceType":"OperationOutcome","issue":[{"severity":"error","code":"security","diagnostics":"(EHR-ERR884) Os dados de autenticação informados são inválidos! Token com identificador ########## não autorizado!"}]}
```

**Comment by kyriosdata** [comment]
curl é muito útil, mas uso depois de validar com o Postman (minha realidade). Acabei de fazer consulta, conforme sugestão [aqui](https://documenter.getpostman.com/view/215332/TVewY47S) e tive resultado satisfatório. Observe que não foi fornecido o valor para o header Authorization, também suponho que esteja faltando "fechar" o header com aspas simples (X-Authorization-Server). Sugiro que elimine qualquer dúvida com a requisição. A requisição está montada corretamente?

**Comment by gustavorps** [comment]
Todo o comando está válido com exceção da detalhe fechar da falta de uma aspas simples. Pois o mesmo returno o número do meu CPF no corpo da resposta da requisição.

Lendo e-book em relação a processo, acredito que é por conta do meu certificado digital não esteja cadastrado junto ao serviço de homologação.

Acredito que terei buscar me adequar e seguir sem acesso ao ambiente de homologação visto o mesmo demanda esforço burocrático, apoio e autorização de gestores.
