### ISSUE TITLE
Cliente rnds-js

### ISSUE THREAD

**Issue by iuribtt** [kyriosdata/rnds#37]
O cliente Node do rnds-js não existe mais, e ou não tem mais suporte?

**Comment by kyriosdata** [comment]
Você detectou algum bug? Está disponível em https://www.npmjs.com/package/rnds

**Comment by iuribtt** [comment]
Sim, tava utilizando mas a Api do busca por CPF nao tava funcionando. Dai foi indicado adicionar o **User-Agent** ao request e o preencha com a informação (nome do sistema)/(versão).
![image](https://user-images.githubusercontent.com/7947746/150833711-42c91cb4-a09b-4b53-b9b0-929027b89680.png)

![image](https://user-images.githubusercontent.com/7947746/150833757-4f006266-d118-4050-98a3-4f434d18e85e.png)


Eu utilizo o **rnds-js** a versão node js"
![image](https://user-images.githubusercontent.com/7947746/150832248-1805de49-7168-4a8f-a808-9d79be5a5596.png)
" 

Entretanto, tenho esse erro do **follow-redirects** eu olhei mas nao vi como resolver:
![image](https://user-images.githubusercontent.com/7947746/150832614-3f5d38b3-70c9-4b2e-bc81-cc5bde2ede9c.png)

`Error: socket hang up
    at connResetException (internal/errors.js:628:14)
    at TLSSocket.socketOnEnd (_http_client.js:499:23)
    at TLSSocket.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
Emitted 'error' event on Writable instance at:
    at ClientRequest.eventHandlers.<computed> (/code/node_modules/follow-redirects/index.js:14:24)
    at ClientRequest.emit (events.js:375:28)
    at TLSSocket.socketOnEnd (_http_client.js:499:9)
    at TLSSocket.emit (events.js:387:35)
    at endReadableNT (internal/streams/readable.js:1317:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'ECONNRESET'
}`

@kyriosdata a gente teria como te acesso ao **rnds-js** a versão node js, o index em especifico?

Iúri

**Comment by kyriosdata** [comment]
Obrigado pelas orientações. Tenho feitos vários ajustes. Vou considerá-las, uma por uma. Sobre a Dúvida "a gente teria como te acesso ao ...", não compreendi?!

Para este header, indicado acima, você está tentando usar o RIA-R ou RIA-C ou outro que desconheço?

**Comment by iuribtt** [comment]
Falo do **index.js** do Cliente da versão node.js. Antes a pasta **rnds-js** estava disponível no repositório, e agora não está mais. 
Estou usando RIA "normal" (deve ser o RIA-R) - https://simplifier.net/redenacionaldedadosemsaude/BRTipoDocumento:
![image](https://user-images.githubusercontent.com/7947746/150892663-a1156042-3791-4499-8237-af4b58b26e6a.png)

Iúri

**Comment by iuribtt** [comment]
@kyriosdata achei, tava na pasta libs, em nem olhei pensei que eram outras dependências do projeto. O que eu quero tava aqui "**libs/rnds-js**". Muito obrigado pela atenção. Irei fechar o issue e atualizar aqui o projeto.
Mais uma vez, muito obrigado.
