### ISSUE TITLE
Integração SOA-BNAFAR.

### ISSUE THREAD

**Issue by erickeliasborges** [kyriosdata/rnds#43]
Bom dia, tudo certo?

Esse projeto contempla somente os métodos de integração das vacinas com o RNDS certo?
Gostaria de tirar um dúvida sobre a integração com o novo WS do SOA-BNAFAR, que antes era o Hórus, será feito algo sobre esse serviço?

Desde já agradeço.
Atenciosamente, Erick Elias Borges.

**Comment by kyriosdata** [comment]
Olá Erick,

contempla resultado de COVID, as vacinas e contemplará as informações que serão trocadas no âmbito da RNDS. 
Ou seja, contempla o que ocorrer via FHIR, não é o caso do SOA-BNAFAR, salvo melhor juízo.

**Comment by erickeliasborges** [comment]
Boa tarde.

Entendido.

Muito obrigado pelo seu retorno,
